import type { Metadata } from "next";
import { Inter, Noto_Sans_Bassa_Vah } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <h2> navbar items</h2>
       <Navbar/>
        {children}
      </body>
    </html>
  );
}
